[package]
name = "binja_coolsigmaker"
version = "0.1.6"
authors = ["unknowntrojan"]
edition = "2024" 

[lib]
crate-type = ["cdylib"]

[dependencies]
# Local Development
# binaryninja = { path = "../binaryninja-api/rust" }

log = "0.4.17"
clipboard = "0.5.0"
rayon = "1.7.0"
iced-x86 = "1.17.0"
strum = { version = "0.26.1", features = ["derive"] }
serde = { version = "1.0.152", features = ["std"] }
serde_json = "1.0.93"
thiserror = "1.0.43"
coolfindpattern = "0.1.6"
binary-search = "0.1.2"


# Dev
# binaryninja = { git = "https://github.com/Vector35/binaryninja-api", branch = "dev" }
# Stable
binaryninja = { git = "https://github.com/Vector35/binaryninja-api", tag = "stable/5.1.8005" }
